ALTER TABLE queue_users ADD COLUMN fmk_id VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE success_users ADD COLUMN fmk_id VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE failure_users ADD COLUMN fmk_id VARCHAR(200) NULL DEFAULT NULL;

ALTER TABLE queue_orgunits ADD COLUMN foa VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE queue_orgunits ADD COLUMN pnr VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE queue_orgunits ADD COLUMN sor VARCHAR(200) NULL DEFAULT NULL;

ALTER TABLE failure_orgunits ADD COLUMN foa VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE failure_orgunits ADD COLUMN pnr VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE failure_orgunits ADD COLUMN sor VARCHAR(200) NULL DEFAULT NULL;

ALTER TABLE success_orgunits ADD COLUMN foa VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE success_orgunits ADD COLUMN pnr VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE success_orgunits ADD COLUMN sor VARCHAR(200) NULL DEFAULT NULL;
