//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationLayer.Adresse
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stoettesystemerne.dk/organisation/6/", ConfigurationName="Adresse.AdressePortType")]
    public interface AdressePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/opret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.opretResponse> opretAsync(Adresse.opretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/importer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.importerResponse> importerAsync(Adresse.importerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/passiver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.passiverResponse> passiverAsync(Adresse.passiverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/laes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.laesResponse> laesAsync(Adresse.laesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/ret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.retResponse> retAsync(Adresse.retRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/slet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.sletResponse> sletAsync(Adresse.sletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/soeg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.soegResponse> soegAsync(Adresse.soegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/adresse/list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Adresse.listResponse> listAsync(Adresse.listRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
    public partial class RequestHeaderType
    {
        
        private string transactionUUIDField;
        
        /// <remarks/>
        public string TransactionUUID
        {
            get
            {
                return this.transactionUUIDField;
            }
            set
            {
                this.transactionUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListInputType
    {
        
        private string[] uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", Order=0)]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class TidspunktType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraenseIndikator", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TidsstempelDatoTid", typeof(System.DateTime), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegOutputType
    {
        
        private StandardReturType standardReturField;
        
        private string[] idListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UUIDIdentifikator", IsNullable=false)]
        public string[] IdListe
        {
            get
            {
                return this.idListeField;
            }
            set
            {
                this.idListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnikReturType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class StandardReturType
    {
        
        private string statusKodeField;
        
        private string fejlbeskedTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string StatusKode
        {
            get
            {
                return this.statusKodeField;
            }
            set
            {
                this.statusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlbeskedTekst
        {
            get
            {
                return this.fejlbeskedTekstField;
            }
            set
            {
                this.fejlbeskedTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikReturType : StandardReturType
    {
        
        private string typeField;
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegVirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UuidLabelInputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikIdType
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URNIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        URNIdentifikator,
        
        /// <remarks/>
        UUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidLabelInputType : UnikIdType
    {
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum AktoerTypeKodeType
    {
        
        /// <remarks/>
        Organisation,
        
        /// <remarks/>
        OrganisationEnhed,
        
        /// <remarks/>
        OrganisationFunktion,
        
        /// <remarks/>
        Bruger,
        
        /// <remarks/>
        ItSystem,
        
        /// <remarks/>
        Interessefaellesskab,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegRegistreringType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum LivscyklusKodeType
    {
        
        /// <remarks/>
        Opstaaet,
        
        /// <remarks/>
        Importeret,
        
        /// <remarks/>
        Passiveret,
        
        /// <remarks/>
        Slettet,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoegInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegInputType
    {
        
        private string foersteResultatReferenceField;
        
        private string maksimalAntalKvantitetField;
        
        private SoegRegistreringType soegRegistreringField;
        
        private SoegVirkningType soegVirkningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FoersteResultatReference
        {
            get
            {
                return this.foersteResultatReferenceField;
            }
            set
            {
                this.foersteResultatReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string MaksimalAntalKvantitet
        {
            get
            {
                return this.maksimalAntalKvantitetField;
            }
            set
            {
                this.maksimalAntalKvantitetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SoegRegistreringType SoegRegistrering
        {
            get
            {
                return this.soegRegistreringField;
            }
            set
            {
                this.soegRegistreringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoegInputType", Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class SoegInputType1 : SoegInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class EgenskabType
    {
        
        private VirkningType virkningField;
        
        private string brugervendtNoegleTekstField;
        
        private string adresseTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public string BrugervendtNoegleTekst
        {
            get
            {
                return this.brugervendtNoegleTekstField;
            }
            set
            {
                this.brugervendtNoegleTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sts:6", Order=2)]
        public string AdresseTekst
        {
            get
            {
                return this.adresseTekstField;
            }
            set
            {
                this.adresseTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class VirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class TilstandListeType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class RelationListeType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RetInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RetInputType", Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class RetInputType1 : RetInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidNoteInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class ImportInputType
    {
        
        private AdresseType adresseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AdresseType Adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class AdresseType : SagDokObjektType
    {
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=0)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistreringType", Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class RegistreringType1 : RegistreringType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RegistreringType
    {
        
        private string noteTekstField;
        
        private System.DateTime tidspunktField;
        
        private bool tidspunktFieldSpecified;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Tidspunkt
        {
            get
            {
                return this.tidspunktField;
            }
            set
            {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TidspunktSpecified
        {
            get
            {
                return this.tidspunktFieldSpecified;
            }
            set
            {
                this.tidspunktFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdresseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesFiltreretOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SagDokObjektType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sts:part:6")]
    public partial class PartType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/6/")]
    public partial class AktoerType : PartType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesFiltreretOutputType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class FiltreretOejebliksbilledeType
    {
        
        private SagDokObjektType objektTypeField;
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SagDokObjektType ObjektType
        {
            get
            {
                return this.objektTypeField;
            }
            set
            {
                this.objektTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=1)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class BasicOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretOutputType : BasicOutputType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class ListOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType[] filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiltreretOejebliksbillede", Order=0)]
        public FiltreretOejebliksbilledeType[] FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class LaesOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FiltreretOejebliksbilledeType FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretInputType
    {
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OpretInputType", Namespace="http://stoettesystemerne.dk/organisation/adresse/6/")]
    public partial class OpretInputType1 : OpretInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.OpretInputType1 OpretInput;
        
        public opretRequest()
        {
        }
        
        public opretRequest(Adresse.RequestHeaderType RequestHeader, Adresse.OpretInputType1 OpretInput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretInput = OpretInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.OpretOutputType OpretOutput;
        
        public opretResponse()
        {
        }
        
        public opretResponse(Adresse.RequestHeaderType RequestHeader, Adresse.OpretOutputType OpretOutput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretOutput = OpretOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.ImportInputType ImportInput;
        
        public importerRequest()
        {
        }
        
        public importerRequest(Adresse.RequestHeaderType RequestHeader, Adresse.ImportInputType ImportInput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportInput = ImportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.BasicOutputType ImportOutput;
        
        public importerResponse()
        {
        }
        
        public importerResponse(Adresse.RequestHeaderType RequestHeader, Adresse.BasicOutputType ImportOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportOutput = ImportOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.UuidNoteInputType PassiverInput;
        
        public passiverRequest()
        {
        }
        
        public passiverRequest(Adresse.RequestHeaderType RequestHeader, Adresse.UuidNoteInputType PassiverInput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverInput = PassiverInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.BasicOutputType PassiverOutput;
        
        public passiverResponse()
        {
        }
        
        public passiverResponse(Adresse.RequestHeaderType RequestHeader, Adresse.BasicOutputType PassiverOutput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverOutput = PassiverOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.LaesInputType LaesInput;
        
        public laesRequest()
        {
        }
        
        public laesRequest(Adresse.RequestHeaderType RequestHeader, Adresse.LaesInputType LaesInput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesInput = LaesInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.LaesOutputType LaesOutput;
        
        public laesResponse()
        {
        }
        
        public laesResponse(Adresse.RequestHeaderType RequestHeader, Adresse.LaesOutputType LaesOutput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesOutput = LaesOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.RetInputType1 RetInput;
        
        public retRequest()
        {
        }
        
        public retRequest(Adresse.RequestHeaderType RequestHeader, Adresse.RetInputType1 RetInput)
        {
            this.RequestHeader = RequestHeader;
            this.RetInput = RetInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.BasicOutputType RetOutput;
        
        public retResponse()
        {
        }
        
        public retResponse(Adresse.RequestHeaderType RequestHeader, Adresse.BasicOutputType RetOutput)
        {
            this.RequestHeader = RequestHeader;
            this.RetOutput = RetOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.UuidNoteInputType SletInput;
        
        public sletRequest()
        {
        }
        
        public sletRequest(Adresse.RequestHeaderType RequestHeader, Adresse.UuidNoteInputType SletInput)
        {
            this.RequestHeader = RequestHeader;
            this.SletInput = SletInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.BasicOutputType SletOutput;
        
        public sletResponse()
        {
        }
        
        public sletResponse(Adresse.RequestHeaderType RequestHeader, Adresse.BasicOutputType SletOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SletOutput = SletOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.SoegInputType1 SoegInput;
        
        public soegRequest()
        {
        }
        
        public soegRequest(Adresse.RequestHeaderType RequestHeader, Adresse.SoegInputType1 SoegInput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegInput = SoegInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.SoegOutputType SoegOutput;
        
        public soegResponse()
        {
        }
        
        public soegResponse(Adresse.RequestHeaderType RequestHeader, Adresse.SoegOutputType SoegOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegOutput = SoegOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.ListInputType ListInput;
        
        public listRequest()
        {
        }
        
        public listRequest(Adresse.RequestHeaderType RequestHeader, Adresse.ListInputType ListInput)
        {
            this.RequestHeader = RequestHeader;
            this.ListInput = ListInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Adresse.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/adresse/6/", Order=0)]
        public Adresse.ListOutputType ListOutput;
        
        public listResponse()
        {
        }
        
        public listResponse(Adresse.RequestHeaderType RequestHeader, Adresse.ListOutputType ListOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ListOutput = ListOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface AdressePortTypeChannel : Adresse.AdressePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AdressePortTypeClient : System.ServiceModel.ClientBase<Adresse.AdressePortType>, Adresse.AdressePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AdressePortTypeClient() : 
                base(AdressePortTypeClient.GetDefaultBinding(), AdressePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Adresse.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdressePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(AdressePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AdressePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdressePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AdressePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdressePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AdressePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdressePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.opretResponse> Adresse.AdressePortType.opretAsync(Adresse.opretRequest request)
        {
            return base.Channel.opretAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.opretResponse> opretAsync(Adresse.RequestHeaderType RequestHeader, Adresse.OpretInputType1 OpretInput)
        {
            Adresse.opretRequest inValue = new Adresse.opretRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.OpretInput = OpretInput;
            return ((Adresse.AdressePortType)(this)).opretAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.importerResponse> Adresse.AdressePortType.importerAsync(Adresse.importerRequest request)
        {
            return base.Channel.importerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.importerResponse> importerAsync(Adresse.RequestHeaderType RequestHeader, Adresse.ImportInputType ImportInput)
        {
            Adresse.importerRequest inValue = new Adresse.importerRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ImportInput = ImportInput;
            return ((Adresse.AdressePortType)(this)).importerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.passiverResponse> Adresse.AdressePortType.passiverAsync(Adresse.passiverRequest request)
        {
            return base.Channel.passiverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.passiverResponse> passiverAsync(Adresse.RequestHeaderType RequestHeader, Adresse.UuidNoteInputType PassiverInput)
        {
            Adresse.passiverRequest inValue = new Adresse.passiverRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.PassiverInput = PassiverInput;
            return ((Adresse.AdressePortType)(this)).passiverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.laesResponse> Adresse.AdressePortType.laesAsync(Adresse.laesRequest request)
        {
            return base.Channel.laesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.laesResponse> laesAsync(Adresse.RequestHeaderType RequestHeader, Adresse.LaesInputType LaesInput)
        {
            Adresse.laesRequest inValue = new Adresse.laesRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.LaesInput = LaesInput;
            return ((Adresse.AdressePortType)(this)).laesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.retResponse> Adresse.AdressePortType.retAsync(Adresse.retRequest request)
        {
            return base.Channel.retAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.retResponse> retAsync(Adresse.RequestHeaderType RequestHeader, Adresse.RetInputType1 RetInput)
        {
            Adresse.retRequest inValue = new Adresse.retRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RetInput = RetInput;
            return ((Adresse.AdressePortType)(this)).retAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.sletResponse> Adresse.AdressePortType.sletAsync(Adresse.sletRequest request)
        {
            return base.Channel.sletAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.sletResponse> sletAsync(Adresse.RequestHeaderType RequestHeader, Adresse.UuidNoteInputType SletInput)
        {
            Adresse.sletRequest inValue = new Adresse.sletRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SletInput = SletInput;
            return ((Adresse.AdressePortType)(this)).sletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.soegResponse> Adresse.AdressePortType.soegAsync(Adresse.soegRequest request)
        {
            return base.Channel.soegAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.soegResponse> soegAsync(Adresse.RequestHeaderType RequestHeader, Adresse.SoegInputType1 SoegInput)
        {
            Adresse.soegRequest inValue = new Adresse.soegRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SoegInput = SoegInput;
            return ((Adresse.AdressePortType)(this)).soegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresse.listResponse> Adresse.AdressePortType.listAsync(Adresse.listRequest request)
        {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresse.listResponse> listAsync(Adresse.RequestHeaderType RequestHeader, Adresse.ListInputType ListInput)
        {
            Adresse.listRequest inValue = new Adresse.listRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ListInput = ListInput;
            return ((Adresse.AdressePortType)(this)).listAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Adresse))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Adresse))
            {
                return new System.ServiceModel.EndpointAddress("http://kombit.dk/sts/organisation/adresse");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AdressePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.Adresse);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AdressePortTypeClient.GetEndpointAddress(EndpointConfiguration.Adresse);
        }
        
        public enum EndpointConfiguration
        {
            
            Adresse,
        }
    }
}
