//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationLayer.Person
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stoettesystemerne.dk/organisation/6/", ConfigurationName="IntegrationLayer.Person.PersonPortType")]
    public interface PersonPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/opret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.opretResponse> opretAsync(IntegrationLayer.Person.opretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/importer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.importerResponse> importerAsync(IntegrationLayer.Person.importerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/passiver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.passiverResponse> passiverAsync(IntegrationLayer.Person.passiverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/laes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.laesResponse> laesAsync(IntegrationLayer.Person.laesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/ret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.retResponse> retAsync(IntegrationLayer.Person.retRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/slet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.sletResponse> sletAsync(IntegrationLayer.Person.sletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/soeg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.soegResponse> soegAsync(IntegrationLayer.Person.soegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/person/list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<IntegrationLayer.Person.listResponse> listAsync(IntegrationLayer.Person.listRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
    public partial class RequestHeaderType
    {
        
        private string transactionUUIDField;
        
        /// <remarks/>
        public string TransactionUUID
        {
            get
            {
                return this.transactionUUIDField;
            }
            set
            {
                this.transactionUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOutputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnikReturType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class StandardReturType
    {
        
        private string statusKodeField;
        
        private string fejlbeskedTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string StatusKode
        {
            get
            {
                return this.statusKodeField;
            }
            set
            {
                this.statusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlbeskedTekst
        {
            get
            {
                return this.fejlbeskedTekstField;
            }
            set
            {
                this.fejlbeskedTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikReturType : StandardReturType
    {
        
        private string typeField;
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ListOutputType", Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class ListOutputType1 : ListOutputType
    {
        
        private FiltreretOejebliksbilledeType[] filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiltreretOejebliksbillede", Order=0)]
        public FiltreretOejebliksbilledeType[] FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class FiltreretOejebliksbilledeType
    {
        
        private SagDokObjektType objektTypeField;
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SagDokObjektType ObjektType
        {
            get
            {
                return this.objektTypeField;
            }
            set
            {
                this.objektTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=1)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesFiltreretOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SagDokObjektType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sts:part:6")]
    public partial class PartType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/6/")]
    public partial class AktoerType : PartType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class PersonType : PartType
    {
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=0)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistreringType", Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class RegistreringType1 : RegistreringType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class EgenskabType
    {
        
        private VirkningType virkningField;
        
        private string brugervendtNoegleTekstField;
        
        private string cPRNummerTekstField;
        
        private string navnTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public string BrugervendtNoegleTekst
        {
            get
            {
                return this.brugervendtNoegleTekstField;
            }
            set
            {
                this.brugervendtNoegleTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CPR-NummerTekst", Namespace="urn:oio:sts:6", Order=2)]
        public string CPRNummerTekst
        {
            get
            {
                return this.cPRNummerTekstField;
            }
            set
            {
                this.cPRNummerTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NavnTekst
        {
            get
            {
                return this.navnTekstField;
            }
            set
            {
                this.navnTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class VirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class TidspunktType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraenseIndikator", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TidsstempelDatoTid", typeof(System.DateTime), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UuidLabelInputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikIdType
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URNIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        URNIdentifikator,
        
        /// <remarks/>
        UUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidLabelInputType : UnikIdType
    {
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum AktoerTypeKodeType
    {
        
        /// <remarks/>
        Organisation,
        
        /// <remarks/>
        OrganisationEnhed,
        
        /// <remarks/>
        OrganisationFunktion,
        
        /// <remarks/>
        Bruger,
        
        /// <remarks/>
        ItSystem,
        
        /// <remarks/>
        Interessefaellesskab,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class TilstandListeType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class RelationListeType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RegistreringType
    {
        
        private string noteTekstField;
        
        private System.DateTime tidspunktField;
        
        private bool tidspunktFieldSpecified;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Tidspunkt
        {
            get
            {
                return this.tidspunktField;
            }
            set
            {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TidspunktSpecified
        {
            get
            {
                return this.tidspunktFieldSpecified;
            }
            set
            {
                this.tidspunktFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum LivscyklusKodeType
    {
        
        /// <remarks/>
        Opstaaet,
        
        /// <remarks/>
        Importeret,
        
        /// <remarks/>
        Passiveret,
        
        /// <remarks/>
        Slettet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesFiltreretOutputType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListInputType
    {
        
        private string[] uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", Order=0)]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegOutputType
    {
        
        private StandardReturType standardReturField;
        
        private string[] idListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UUIDIdentifikator", IsNullable=false)]
        public string[] IdListe
        {
            get
            {
                return this.idListeField;
            }
            set
            {
                this.idListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegVirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegRegistreringType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoegInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegInputType
    {
        
        private string foersteResultatReferenceField;
        
        private string maksimalAntalKvantitetField;
        
        private SoegRegistreringType soegRegistreringField;
        
        private SoegVirkningType soegVirkningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FoersteResultatReference
        {
            get
            {
                return this.foersteResultatReferenceField;
            }
            set
            {
                this.foersteResultatReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string MaksimalAntalKvantitet
        {
            get
            {
                return this.maksimalAntalKvantitetField;
            }
            set
            {
                this.maksimalAntalKvantitetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SoegRegistreringType SoegRegistrering
        {
            get
            {
                return this.soegRegistreringField;
            }
            set
            {
                this.soegRegistreringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoegInputType", Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class SoegInputType1 : SoegInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RetInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RetInputType", Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class RetInputType1 : RetInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidNoteInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class ImportInputType
    {
        
        private PersonType personField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonType Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class BasicOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretOutputType : BasicOutputType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class LaesOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FiltreretOejebliksbilledeType FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretInputType
    {
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OpretInputType", Namespace="http://stoettesystemerne.dk/organisation/person/6/")]
    public partial class OpretInputType1 : OpretInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.OpretInputType1 OpretInput;
        
        public opretRequest()
        {
        }
        
        public opretRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.OpretInputType1 OpretInput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretInput = OpretInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.OpretOutputType OpretOutput;
        
        public opretResponse()
        {
        }
        
        public opretResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.OpretOutputType OpretOutput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretOutput = OpretOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.ImportInputType ImportInput;
        
        public importerRequest()
        {
        }
        
        public importerRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.ImportInputType ImportInput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportInput = ImportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.BasicOutputType ImportOutput;
        
        public importerResponse()
        {
        }
        
        public importerResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.BasicOutputType ImportOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportOutput = ImportOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.UuidNoteInputType PassiverInput;
        
        public passiverRequest()
        {
        }
        
        public passiverRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.UuidNoteInputType PassiverInput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverInput = PassiverInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.BasicOutputType PassiverOutput;
        
        public passiverResponse()
        {
        }
        
        public passiverResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.BasicOutputType PassiverOutput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverOutput = PassiverOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.LaesInputType LaesInput;
        
        public laesRequest()
        {
        }
        
        public laesRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.LaesInputType LaesInput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesInput = LaesInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.LaesOutputType LaesOutput;
        
        public laesResponse()
        {
        }
        
        public laesResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.LaesOutputType LaesOutput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesOutput = LaesOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.RetInputType1 RetInput;
        
        public retRequest()
        {
        }
        
        public retRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.RetInputType1 RetInput)
        {
            this.RequestHeader = RequestHeader;
            this.RetInput = RetInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.BasicOutputType RetOutput;
        
        public retResponse()
        {
        }
        
        public retResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.BasicOutputType RetOutput)
        {
            this.RequestHeader = RequestHeader;
            this.RetOutput = RetOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.UuidNoteInputType SletInput;
        
        public sletRequest()
        {
        }
        
        public sletRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.UuidNoteInputType SletInput)
        {
            this.RequestHeader = RequestHeader;
            this.SletInput = SletInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.BasicOutputType SletOutput;
        
        public sletResponse()
        {
        }
        
        public sletResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.BasicOutputType SletOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SletOutput = SletOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.SoegInputType1 SoegInput;
        
        public soegRequest()
        {
        }
        
        public soegRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.SoegInputType1 SoegInput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegInput = SoegInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.SoegOutputType SoegOutput;
        
        public soegResponse()
        {
        }
        
        public soegResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.SoegOutputType SoegOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegOutput = SoegOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.ListInputType ListInput;
        
        public listRequest()
        {
        }
        
        public listRequest(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.ListInputType ListInput)
        {
            this.RequestHeader = RequestHeader;
            this.ListInput = ListInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public IntegrationLayer.Person.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/person/6/", Order=0)]
        public IntegrationLayer.Person.ListOutputType1 ListOutput;
        
        public listResponse()
        {
        }
        
        public listResponse(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.ListOutputType1 ListOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ListOutput = ListOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface PersonPortTypeChannel : IntegrationLayer.Person.PersonPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PersonPortTypeClient : System.ServiceModel.ClientBase<IntegrationLayer.Person.PersonPortType>, IntegrationLayer.Person.PersonPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PersonPortTypeClient() : 
                base(PersonPortTypeClient.GetDefaultBinding(), PersonPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Person.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(PersonPortTypeClient.GetBindingForEndpoint(endpointConfiguration), PersonPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PersonPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PersonPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.opretResponse> IntegrationLayer.Person.PersonPortType.opretAsync(IntegrationLayer.Person.opretRequest request)
        {
            return base.Channel.opretAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.opretResponse> opretAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.OpretInputType1 OpretInput)
        {
            IntegrationLayer.Person.opretRequest inValue = new IntegrationLayer.Person.opretRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.OpretInput = OpretInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).opretAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.importerResponse> IntegrationLayer.Person.PersonPortType.importerAsync(IntegrationLayer.Person.importerRequest request)
        {
            return base.Channel.importerAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.importerResponse> importerAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.ImportInputType ImportInput)
        {
            IntegrationLayer.Person.importerRequest inValue = new IntegrationLayer.Person.importerRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ImportInput = ImportInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).importerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.passiverResponse> IntegrationLayer.Person.PersonPortType.passiverAsync(IntegrationLayer.Person.passiverRequest request)
        {
            return base.Channel.passiverAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.passiverResponse> passiverAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.UuidNoteInputType PassiverInput)
        {
            IntegrationLayer.Person.passiverRequest inValue = new IntegrationLayer.Person.passiverRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.PassiverInput = PassiverInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).passiverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.laesResponse> IntegrationLayer.Person.PersonPortType.laesAsync(IntegrationLayer.Person.laesRequest request)
        {
            return base.Channel.laesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.laesResponse> laesAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.LaesInputType LaesInput)
        {
            IntegrationLayer.Person.laesRequest inValue = new IntegrationLayer.Person.laesRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.LaesInput = LaesInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).laesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.retResponse> IntegrationLayer.Person.PersonPortType.retAsync(IntegrationLayer.Person.retRequest request)
        {
            return base.Channel.retAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.retResponse> retAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.RetInputType1 RetInput)
        {
            IntegrationLayer.Person.retRequest inValue = new IntegrationLayer.Person.retRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RetInput = RetInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).retAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.sletResponse> IntegrationLayer.Person.PersonPortType.sletAsync(IntegrationLayer.Person.sletRequest request)
        {
            return base.Channel.sletAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.sletResponse> sletAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.UuidNoteInputType SletInput)
        {
            IntegrationLayer.Person.sletRequest inValue = new IntegrationLayer.Person.sletRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SletInput = SletInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).sletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.soegResponse> IntegrationLayer.Person.PersonPortType.soegAsync(IntegrationLayer.Person.soegRequest request)
        {
            return base.Channel.soegAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.soegResponse> soegAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.SoegInputType1 SoegInput)
        {
            IntegrationLayer.Person.soegRequest inValue = new IntegrationLayer.Person.soegRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SoegInput = SoegInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).soegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationLayer.Person.listResponse> IntegrationLayer.Person.PersonPortType.listAsync(IntegrationLayer.Person.listRequest request)
        {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationLayer.Person.listResponse> listAsync(IntegrationLayer.Person.RequestHeaderType RequestHeader, IntegrationLayer.Person.ListInputType ListInput)
        {
            IntegrationLayer.Person.listRequest inValue = new IntegrationLayer.Person.listRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ListInput = ListInput;
            return ((IntegrationLayer.Person.PersonPortType)(this)).listAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Person))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Person))
            {
                return new System.ServiceModel.EndpointAddress("http://kombit.dk/sts/organisation/person");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PersonPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.Person);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PersonPortTypeClient.GetEndpointAddress(EndpointConfiguration.Person);
        }
        
        public enum EndpointConfiguration
        {
            
            Person,
        }
    }
}
